---
# Test ServiceAccount - Compliant Configuration
# This ServiceAccount should be allowed by the restrict-workload-identity policy
# Replace <project-id> with your actual GCP project ID
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-sa-compliant
  namespace: default
  annotations:
    iam.gke.io/gcp-service-account: "prod-gsa@my-project-id.iam.gserviceaccount.com"

---
# Test ServiceAccount - Non-Compliant (Missing Annotation)
# This ServiceAccount should be BLOCKED by the restrict-workload-identity policy
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-sa-no-annotation
  namespace: default
  # Missing iam.gke.io/gcp-service-account annotation

---
# Test ServiceAccount - Non-Compliant (Wrong Format)
# This ServiceAccount should be BLOCKED by the restrict-workload-identity policy
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-sa-wrong-format
  namespace: default
  annotations:
    iam.gke.io/gcp-service-account: "dev-sa@my-project-id.iam.gserviceaccount.com"
    # Wrong prefix - should be "prod-gsa@" not "dev-sa@"

---
# Test ServiceAccount - Non-Compliant (Invalid Format)
# This ServiceAccount should be BLOCKED by the restrict-workload-identity policy
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-sa-invalid-format
  namespace: default
  annotations:
    iam.gke.io/gcp-service-account: "prod-gsa@invalid-format"
    # Missing .iam.gserviceaccount.com suffix

