apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: default-resources
spec:
  validationFailureAction: Enforce
  background: true
  rules:
  - name: add-defaults
    match:
      any:
      - resources:
          kinds: [Pod]
    mutate:
      patchStrategicMerge:
        spec:
          containers:
          - (name): "*"
            resources:
              limits:
                +(cpu): "500m"
                +(memory): "512Mi"
              requests:
                +(cpu): "250m"
                +(memory): "256Mi"
